do not fail on ECONNRESET
vdemedes/net-socket pull request #1
Opened 2016-11-18 03:33 UTC by mrose17

when talking to the OSRAM Lightify bridge, I see intermittent ECONNRESET ... so the package no retries on that in addition to ECONNREFUSED

2016-11-18 06:13 UTC, vdemedes commented
Good suggestion. Could you add a test for that?

2016-11-19 21:42 UTC, mrose17 commented
thank. the problem is writing some server code that emulates that behavior. getting an ECONNREFUSED is easy (just try connect to a port where nothing is listening), but an ECONNRESET requires something to be listening, to accept the connection, and then to abruptly close the connection.

i can probably figure out a way to make that happen, but it's probably not straight-forward...

2016-11-27 18:19 UTC, vdemedes commented
I think I'll make an exception and accept this without tests (only with a minor modification). Thanks!

2016-11-27 18:20 UTC, vadimdemedes requested changes

2016-11-27 18:20 UTC, vdemedes commented on index.js
> +    if ((err.code === 'ECONNREFUSED') || (err.code === 'ECONNRESET')) {
brackets aren't necessary.

2016-11-28 16:46 UTC, mrose17 commented
change made.

still trying to figure out how to build a test case.

also, you might wish to run `jshint *.js` ... there are a couple of things it reports.

best,

/mtr

2016-11-28 17:59 UTC, vdemedes commented
I'll need to think what I should do with this module, either discontinue it (and recommend retry kind of modules) or update it.

2016-11-28 17:59 UTC, merged

2016-11-28 17:59 UTC, vdemedes commented
Thanks for the PR ;)

2016-11-28 18:00 UTC, vdemedes commented
Published as `net-socket@1.1.0`.

2016-11-28 18:18 UTC, mrose17 commented
many thanks!